require("prototypes.recipe")
require("prototypes.items")
require("prototypes.technology")
require("prototypes.achievements")
require("prototypes.equipment")
require("prototypes.projectiles")
require("prototypes.science_bottles")
require("prototypes.modules")
require("music.music")

require("prototypes.natalie_facts.fact_tapes")
require("prototypes.natalie_facts.fact_techs")

require("__base__.prototypes.entity.sounds")
require("__base__.prototypes.item_sounds")